# Generated by Django 4.2 on 2023-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='Index first name')),
                ('name2', models.CharField(max_length=100, verbose_name='Index second name')),
                ('text', models.TextField(verbose_name='Index text')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='Index image')),
            ],
        ),
        migrations.CreateModel(
            name='Index2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='Index first name')),
                ('name2', models.CharField(max_length=100, verbose_name='Index second name')),
                ('text', models.TextField(verbose_name='Index text')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='Index image')),
            ],
        ),
        migrations.CreateModel(
            name='Index3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='Index first name')),
                ('name2', models.CharField(max_length=100, verbose_name='Index second name')),
                ('text', models.TextField(verbose_name='Index text')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='Index image')),
            ],
        ),
    ]
