# Generated by Django 4.2 on 2023-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=100, verbose_name='About name')),
                ('text', models.TextField(verbose_name='About')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='About image')),
            ],
        ),
        migrations.CreateModel(
            name='IndexAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Appoitment name')),
                ('text', models.TextField(verbose_name='Appoitment text')),
            ],
        ),
        migrations.CreateModel(
            name='IndexBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=100, verbose_name='Blog name')),
                ('text', models.TextField(verbose_name='Blog')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='Blog image')),
                ('name', models.CharField(max_length=100, verbose_name='Blog name')),
                ('about', models.TextField(verbose_name='Blog')),
                ('data', models.DateField(verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='IndexCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=100, verbose_name='Customers name')),
                ('text', models.TextField(verbose_name='About')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='Customers image')),
                ('name', models.CharField(max_length=100, verbose_name='Customers name')),
                ('about', models.TextField(verbose_name='Customers')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=100, verbose_name='Price name')),
                ('text', models.TextField(verbose_name='Text')),
                ('name', models.CharField(max_length=100, verbose_name='Price name')),
                ('about', models.TextField(verbose_name='Text')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='IndexServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=100, verbose_name='Services title')),
                ('name', models.CharField(max_length=100, verbose_name='Services first name')),
                ('text', models.TextField(verbose_name='Srvices first text')),
                ('img', models.ImageField(upload_to='pictures', verbose_name='Service image')),
            ],
        ),
        migrations.DeleteModel(
            name='Index2',
        ),
        migrations.DeleteModel(
            name='Index3',
        ),
    ]
