# Generated by Django 4.2 on 2023-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_indexabout_indexappointment_indexblog_indexcustomers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('text', models.TextField(verbose_name='Contact text')),
            ],
        ),
    ]
